#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Sun Jan  3 01:05:29 2010

import wx

# begin wxGlade: extracode
# end wxGlade



class EditProtoDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: EditProtoDialog.__init__
        kwds["style"] = wx.CAPTION|wx.RESIZE_BORDER|wx.CLOSE_BOX|wx.THICK_FRAME
        wx.Dialog.__init__(self, *args, **kwds)
        self.pnEditPanel = ProtoEditPanel(self, -1)
        self.btApply = wx.Button(self, wx.ID_APPLY, "")
        self.btCancel = wx.Button(self, wx.ID_CANCEL, "")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: EditProtoDialog.__set_properties
        self.SetTitle("Edit Prototype")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: EditProtoDialog.__do_layout
        gdAll = wx.FlexGridSizer(2, 1, 5, 5)
        gdActions = wx.BoxSizer(wx.HORIZONTAL)
        gdAll.Add(self.pnEditPanel, 1, wx.EXPAND, 0)
        gdActions.Add(self.btApply, 0, wx.ALIGN_RIGHT, 0)
        gdActions.Add(self.btCancel, 0, wx.ALIGN_RIGHT, 0)
        gdAll.Add(gdActions, 1, wx.EXPAND|wx.ALIGN_CENTER_HORIZONTAL|wx.ALIGN_CENTER_VERTICAL, 0)
        self.SetSizer(gdAll)
        gdAll.Fit(self)
        gdAll.AddGrowableRow(0)
        gdAll.AddGrowableCol(0)
        self.Layout()
        # end wxGlade

# end of class EditProtoDialog


class dlgEditProtoDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # content of this block not found: did you rename this class?
        pass

    def __set_properties(self):
        # content of this block not found: did you rename this class?
        pass

    def __do_layout(self):
        # content of this block not found: did you rename this class?
        pass

# end of class dlgEditProtoDialog


class NewProtoDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: NewProtoDialog.__init__
        kwds["style"] = wx.CAPTION|wx.RESIZE_BORDER|wx.CLOSE_BOX|wx.THICK_FRAME
        wx.Dialog.__init__(self, *args, **kwds)
        self.pnEditPanel = ProtoEditPanel(self, -1)
        self.btNew = wx.Button(self, wx.ID_NEW, "")
        self.btCancel = wx.Button(self, wx.ID_CANCEL, "")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: NewProtoDialog.__set_properties
        self.SetTitle("New Node Prototype")
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: NewProtoDialog.__do_layout
        gdAll = wx.FlexGridSizer(2, 1, 5, 5)
        gdActions = wx.BoxSizer(wx.HORIZONTAL)
        gdAll.Add(self.pnEditPanel, 1, wx.EXPAND, 0)
        gdActions.Add(self.btNew, 0, 0, 0)
        gdActions.Add(self.btCancel, 0, 0, 0)
        gdAll.Add(gdActions, 1, wx.EXPAND, 0)
        self.SetSizer(gdAll)
        gdAll.Fit(self)
        gdAll.AddGrowableRow(0)
        gdAll.AddGrowableCol(0)
        self.Layout()
        # end wxGlade

# end of class NewProtoDialog


class ProtoEditPanel(wx.Panel):
    def __init__(self, *args, **kwds):
        # begin wxGlade: ProtoEditPanel.__init__
        kwds["style"] = wx.TAB_TRAVERSAL
        wx.Panel.__init__(self, *args, **kwds)
        self.lbType = wx.StaticText(self, -1, "Typename")
        self.txTypename = wx.TextCtrl(self, -1, "")
        self.lbSubtype = wx.StaticText(self, -1, "Subtype")
        self.cbHasSubtypes = wx.CheckBox(self, -1, "Has subtypes?")
        self.liSubtypes = wx.ListBox(self, -1, choices=[])
        self.btNewSubtype = wx.Button(self, wx.ID_NEW, "")
        self.btDelSubtype = wx.Button(self, wx.ID_DELETE, "")
        self.lbAttributes = wx.StaticText(self, -1, "Attributes")
        self.rbAttributes = wx.RadioBox(self, -1, "", choices=["NOT DEFINED", "STATIC_PORTS", "OUTPORTS_DEPEND_ON_INPORT", "ALLPORTS_DEPEND_ON_STATE", "PORTS_DEPEND_ON_PARAMETER", "OUTPORTS_SAME_AS_INPORTS", "OUTPORTS_SAME_AS_INPORTS_MIXIN"], majorDimension=0, style=wx.RA_SPECIFY_ROWS)
        self.lbPorts = wx.StaticText(self, -1, "Ports")
        self.liInports = wx.ListBox(self, -1, choices=[])
        self.liOutports = wx.ListBox(self, -1, choices=[])
        self.btNewInport = wx.Button(self, wx.ID_NEW, "")
        self.btDelInport = wx.Button(self, wx.ID_DELETE, "")
        self.btNewOutport = wx.Button(self, wx.ID_NEW, "")
        self.btDelOutport = wx.Button(self, wx.ID_DELETE, "")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: ProtoEditPanel.__set_properties
        self.rbAttributes.SetSelection(0)
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: ProtoEditPanel.__do_layout
        szGrid = wx.FlexGridSizer(7, 2, 0, 5)
        gdPorts = wx.FlexGridSizer(2, 2, 0, 4)
        gdButtonOutport = wx.GridSizer(1, 2, 0, 2)
        gdBtInport = wx.GridSizer(1, 2, 0, 2)
        gdSubtypes = wx.FlexGridSizer(3, 1, 0, 0)
        gdSubtypeBtns = wx.GridSizer(1, 2, 0, 0)
        szGrid.Add(self.lbType, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        szGrid.Add(self.txTypename, 0, wx.EXPAND, 0)
        szGrid.Add(self.lbSubtype, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        gdSubtypes.Add(self.cbHasSubtypes, 0, 0, 0)
        gdSubtypes.Add(self.liSubtypes, 0, wx.EXPAND, 0)
        gdSubtypeBtns.Add(self.btNewSubtype, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        gdSubtypeBtns.Add(self.btDelSubtype, 0, 0, 0)
        gdSubtypes.Add(gdSubtypeBtns, 1, wx.EXPAND, 0)
        gdSubtypes.AddGrowableRow(1)
        gdSubtypes.AddGrowableCol(0)
        szGrid.Add(gdSubtypes, 1, wx.EXPAND, 0)
        szGrid.Add(self.lbAttributes, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        szGrid.Add(self.rbAttributes, 0, wx.EXPAND, 0)
        szGrid.Add(self.lbPorts, 0, 0, 0)
        gdPorts.Add(self.liInports, 0, wx.EXPAND, 0)
        gdPorts.Add(self.liOutports, 0, wx.EXPAND, 0)
        gdBtInport.Add(self.btNewInport, 0, 0, 0)
        gdBtInport.Add(self.btDelInport, 0, 0, 0)
        gdPorts.Add(gdBtInport, 1, wx.EXPAND, 0)
        gdButtonOutport.Add(self.btNewOutport, 0, 0, 0)
        gdButtonOutport.Add(self.btDelOutport, 0, 0, 0)
        gdPorts.Add(gdButtonOutport, 1, wx.EXPAND, 0)
        gdPorts.AddGrowableRow(0)
        szGrid.Add(gdPorts, 1, wx.EXPAND, 0)
        self.SetSizer(szGrid)
        szGrid.Fit(self)
        szGrid.AddGrowableRow(1)
        szGrid.AddGrowableRow(3)
        szGrid.AddGrowableCol(1)
        # end wxGlade

# end of class ProtoEditPanel


